# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Superhero Data Science'
copyright = '2025, Dario Malchiodi'
author = 'Dario Malchiodi'

# The full version, including alpha/beta/rc tags
release = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.


extensions = [ 'myst_parser',
               'sphinx_book_theme', 
               'sphinx.ext.mathjax', 'sphinx_exercise', 'sphinx_tabs.tabs',
               'sphinxcontrib.bibtex',
               'sphinx_external_toc',
               'sphinx_proof',
                ]

# nb_code_cell_render_options = {
#     'python3': { 'lexer': 'python' }
# }
# pygments_style = 'friendly'  # or "friendly", "monokai", etc.
# highlight_language = 'python'


bibtex_bibfiles = ['../references.bib']
bibtex_reference_style = 'author_year'

# myst_enable_extensions = [
#     'html_admonition',
#     'html_image',
#     'colon_fence',
#     'amsmath',
#     'dollarmath',
#     'tabs'
# ]

myst_enable_extensions = [ 'deflist' ]

myst_config = {
    "enable_extensions": [
        "amsmath",
        "dollarmath",
        "html_admonition",
        "html_image",
        "colon_fence",
        "tabs",
        "deflist",
        "linkify",
        "replacements",
        "substitution",
        "smartquotes",
        "tasklist",
    ],
    "heading_anchors": 3,
    "number_code_blocks": ["python", "bash", "shell", "javascript", "css", "html", "yaml", "json", "xml", "sql", "r", "julia", "matlab", "rust", "go", "java", "cpp", "c"],
    "title_to_header": True,
}


# myst_heading_start_level = 2

root_doc = 'landing'

external_toc_path = '_toc.yml'
external_toc_exclude_missing = False

# Enable figure and table numbering within chapters
numfig = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Tableau %s', 
    'code-block': 'Algorithme %s',
    'section': 'Paragraphe %s'
}

# Figure and table numbering configuration
# Note: Chapter-relative numbering (X.Y format) is not compatible with current toctree structure
# where sections are nested under chapters. Using global numbering provides consistent 
# numbering across the entire document while maintaining proper cross-references.
numfig_secnum_depth = 0  # Use global numbering (Tabella 1, Tabella 2, Figura 1, etc.)

# Additional numbering and cross-reference settings
numbered_toctree = True
myst_heading_anchors = 3
myst_number_code_blocks = []

# Enable automatic section labels with numbering
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = None

# Basic settings for cross-references
html_secnumber_suffix = '. '
toc_object_entries_show_parents = 'hide'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['../_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'
locale_dirs = ['../locales/'] # Path to your .po/.mo files
gettext_compact = False

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_book_theme'
html_title = 'Superhero Data Science'
html_logo = '../_static/img/logo.png'
html_favicon = '../_static/img/sds.ico'

html_theme_options = {
    'home_page_in_toc': True,
    'show_toc_level': 3,
    'show_navbar_depth': 3,
    'number_toc': True,
    'pygments_light_style': 'abap',
    'pygments_dark_style': 'native',
    # "extra_footer": "<p>Footer HTML</p>",
}

html_context = {
    "language_switcher": """
        <div style="text-align: right;">
            <a href="/it/index.html">Italiano</a> |
            <a href="/en/index.html">English</a> |
            <strong>Français</strong>
        </div>
    """,
    "show_code_label": "Afficher le code",
    "hide_code_label": "Masquer le code",
    "pyscript_wait_label": "Attendre le chargement de PyScript"
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom.css', 'custom_fr.css']

html_js_files = [
    'custom.js',
    # 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
    # 'https://pyscript.net/releases/2025.5.1/core.js'
    # "https://cdn.jsdelivr.net/npm/vega@5",
    # "https://cdn.jsdelivr.net/npm/vega-lite@5",
    # "https://cdn.jsdelivr.net/npm/vega-embed@6",
]

mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"


suppress_warnings = [
    # 'myst-nb.lexer',
    # 'image.not_readable'
]


def setup(app):
    print(">>> sphinx_tabs.tabs extension loaded")