name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Fix sphinx-proof
      run: |
        sudo apt-get install gettext && \
        ls -lsa /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof && \
        git clone https://github.com/dariomalchiodi/sphinx-proof.git && \
        cd sphinx-proof && \
        ls sphinx_proof/translations && \
        echo "generating mo files" && \
        python sphinx_proof/translations/_convert.py && \
        ls sphinx_proof/translations && \
        cp -r sphinx_proof/translations /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof/translations && \
        ls -lsa /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof && \
        ls -lsa /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof/translations && \
        ls -lsa /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof/translations/locales && \
        ls -lsa /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof/translations/locales/it/LC_MESSAGES && \
        cat /opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/sphinx_proof/translations/locales/it/LC_MESSAGES/proof.mo

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build sds

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sds/_build/html
